"""
generate_alphax_schedule.py
Generates AlphaX_Project_Schedule.csv and AlphaX_Project_Schedule.xml
Project AlphaX: Bosch Battery Division -> NewCo Battery (Stand Alone, No Merger Zone)
19 months: 01 Jun 2026 -> 31 Dec 2027 | 35 sites | 3,000 users | ~200 apps | ~2,500 devices

Run:  python generate_alphax_schedule.py
Output: AlphaX\AlphaX_Project_Schedule.csv
        AlphaX\AlphaX_Project_Schedule.xml
"""

import csv
import os
import sys
from pathlib import Path

# ── Patch path so generate_msp_xml can be imported ───────────────────────────
HERE = Path(__file__).parent
OUT_DIR = HERE / "AlphaX"
OUT_DIR.mkdir(exist_ok=True)

CSV_PATH = OUT_DIR / "AlphaX_Project_Schedule.csv"
XML_PATH = OUT_DIR / "AlphaX_Project_Schedule.xml"

# ── Task data ─────────────────────────────────────────────────────────────────
# Columns: ID, Outline Level, Name, Duration, Start, Finish,
#          Predecessors, Resource Names, Notes, Milestone
TASKS = [
    # ── PHASE 1: Initialization  01 Jun 2026 – 31 Aug 2026 ──────────────────
    (1,  1, "Phase 1 - Initialization",                                   "65 days",  "06/01/26", "08/31/26", "",                  "Bosch IT + NewCo + KPMG",                        "",                                                                                                           "No"),
    (2,  2, "1.1 Project Setup and Governance",                           "20 days",  "06/01/26", "06/26/26", "",                  "Bosch IT PM + KPMG",                             "",                                                                                                           "No"),
    (3,  3, "Appoint AlphaX Programme Leads (Bosch and NewCo)",           "10 days",  "06/01/26", "06/12/26", "",                  "Bosch CIO + NewCo Management",                   "",                                                                                                           "No"),
    (4,  3, "Establish AlphaX Steering Committee",                        "7 days",   "06/08/26", "06/16/26", "3",                 "Bosch + NewCo Senior Mgmt",                      "",                                                                                                           "No"),
    (5,  3, "Define RACI and Governance Model",                           "10 days",  "06/08/26", "06/19/26", "3",                 "KPMG + IT PM",                                   "",                                                                                                           "No"),
    (6,  3, "Set Up PMO Tools and SharePoint Collaboration Site",         "15 days",  "06/15/26", "07/03/26", "3",                 "PMO + KPMG",                                     "",                                                                                                           "No"),
    (7,  3, "Onboard KPMG PMO Team",                                      "10 days",  "06/15/26", "06/26/26", "3",                 "KPMG",                                           "",                                                                                                           "No"),
    (8,  2, "Signing - Frozen Zone Activated",                            "0 days",   "06/15/26", "06/15/26", "3",                 "Bosch + NewCo Executive",                        "No Battery IT production changes without SteerCo approval from this date",                                   "Yes"),
    (9,  2, "1.2 Battery IT Landscape Assessment - 35 Sites",             "35 days",  "06/29/26", "08/14/26", "3",                 "Bosch IT + KPMG",                                "35 Battery sites: EMEA ~15 / AP ~12 / AM ~8",                                                               "No"),
    (10, 3, "Battery IT Inventory Request (Apps / Infrastructure / Devices)", "10 days", "06/29/26", "07/10/26", "5",             "Bosch IT PM",                                    "",                                                                                                           "No"),
    (11, 3, "Location List - 35 Battery Sites (EMEA / AP / AM)",          "20 days",  "07/01/26", "07/28/26", "10",                "Bosch IT + Facilities",                          "EMEA ~15 sites; AP ~12 sites; AM ~8 sites",                                                                  "No"),
    (12, 3, "Legal Entity Identification - NewCo Battery Registration",   "20 days",  "07/01/26", "07/28/26", "10",                "Legal + Finance",                                "NewCo legal entity registration critical; watch for Mexico and China delays",                                  "No"),
    (13, 3, "Identify Battery IT Dependencies on Bosch Shared Services",  "25 days",  "07/13/26", "08/14/26", "11",                "Bosch IT Architects",                            "Identifies all Bosch shared services used by Battery; forms full TSA scope",                                  "No"),
    (14, 2, "1.3 Project Charter and Scope Definition",                   "20 days",  "08/03/26", "08/28/26", "9",                 "Bosch IT PM + KPMG",                             "",                                                                                                           "No"),
    (15, 3, "Draft AlphaX Project Charter",                               "10 days",  "08/03/26", "08/14/26", "9",                 "KPMG + Bosch IT PM",                             "",                                                                                                           "No"),
    (16, 3, "Define Scope Boundaries - Battery IT Only (Stand Alone)",    "10 days",  "08/10/26", "08/21/26", "11",                "KPMG + Bosch IT",                                "3000 employees; ~2500 client devices; ~200 apps; Full Stand Alone - no Merger Zone",                         "No"),
    (17, 3, "Guiding Principles Workshop - First Make It Work",           "5 days",   "08/17/26", "08/21/26", "15",                "All WS Leads",                                   "",                                                                                                           "No"),
    (18, 3, "TSA Framework Preliminary Scope (Bosch-operated TSA)",       "10 days",  "08/17/26", "08/28/26", "15",                "Legal + IT PM",                                  "Bosch operates all Battery IT during TSA until Dec 2027; define scope and exit dates",                        "No"),
    (19, 3, "Project Charter Approval",                                   "5 days",   "08/25/26", "08/31/26", "15,16,17,18",       "Steering Committee",                             "",                                                                                                           "Yes"),
    (20, 2, "QG1 - Initialization Quality Gate",                         "0 days",   "08/31/26", "08/31/26", "19",                "Steering Committee",                             "Charter approved; full inventory confirmed; governance accepted; proceed to Concept Phase",                    "Yes"),

    # ── PHASE 2: Concept  01 Sep 2026 – 30 Nov 2026 ─────────────────────────
    (21, 1, "Phase 2 - Concept",                                          "65 days",  "09/01/26", "11/30/26", "20",                "All Workstreams + KPMG",                         "",                                                                                                           "No"),
    (22, 2, "2.1 Detailed As-Is Analysis",                                "50 days",  "09/01/26", "11/10/26", "20",                "Bosch IT + KPMG",                                "",                                                                                                           "No"),
    (23, 3, "Application Landscape Inventory (LeanIX) ~200 Battery Apps", "35 days",  "09/01/26", "10/19/26", "20",                "Bosch IT Architects + KPMG",                     "Battery-specific apps only; flag Bosch shared platform dependencies",                                        "No"),
    (24, 3, "IT Infrastructure As-Is Mapping - 35 Battery Sites",         "35 days",  "09/01/26", "10/19/26", "20",                "Bosch Infra Team",                               "Site surveys for top 10 locations; EMEA and AP hubs prioritised",                                           "No"),
    (25, 3, "ERP Landscape Analysis - Battery SAP Scope",                 "35 days",  "09/01/26", "10/19/26", "20",                "Bosch ERP Team + KPMG",                          "Identify Battery-specific vs shared Bosch SAP systems; scope separation complexity",                        "No"),
    (26, 3, "Data Ownership and Separation Rules",                        "25 days",  "10/20/26", "11/23/26", "23,25",             "KPMG + Legal",                                   "Define data classification; confirm non-selective migration approach",                                        "No"),
    (27, 3, "Contract and Licence Inventory (~200 App Licences)",         "35 days",  "09/01/26", "10/19/26", "20",                "Bosch Procurement + IT",                         "Change of control clause review; FOSS compliance audit; ~2500 device licences",                             "No"),
    (28, 3, "HR IT Systems Mapping - 3000 Battery Employees",             "25 days",  "09/01/26", "10/05/26", "20",                "Bosch HR IT",                                    "Country-by-country HR rules; payroll separation per region",                                                 "No"),
    (29, 3, "OT and Production IT Assessment - Battery Manufacturing",    "25 days",  "09/14/26", "10/16/26", "20",                "Bosch OT + Production IT",                       "Battery OT systems; MES; safety certifications; ICS/SCADA",                                                 "No"),
    (30, 3, "Country-Specific IT Requirements (Germany / China / India / Mexico)", "20 days", "09/21/26", "10/16/26", "20",       "Regional IT Leads",                              "Germany works council; China PIPL; India RBIN waiver needed; Mexico SAT delays",                             "No"),
    (31, 2, "2.2 NewCo Stand-Alone Architecture Design",                  "55 days",  "09/14/26", "11/27/26", "23,24",             "Bosch IT Architects + KPMG",                     "Stand Alone model - no Merger Zone; direct to NewCo environment",                                           "No"),
    (32, 3, "NewCo Architecture Concept Workshop (Stand Alone)",          "10 days",  "09/14/26", "09/25/26", "23",                "Bosch + NewCo Architects",                       "Confirm Stand Alone approach; no Merger Zone; define NewCo IT target state",                                 "No"),
    (33, 3, "WAN and LAN Architecture Design - 35 Battery Sites",         "20 days",  "09/28/26", "10/23/26", "32",                "Bosch Infra + KPMG",                             "Hub-and-spoke model; 1 regional co-lo; 4-6 month WAN lead time; order at QG2",                             "No"),
    (34, 3, "Active Directory Design - NewCo Battery Forest",             "20 days",  "09/28/26", "10/23/26", "32",                "Bosch AD Team",                                  "New AD forest for NewCo Battery; fully separate from Bosch corporate AD",                                   "No"),
    (35, 3, "M365 and Azure Tenant Design - NewCo Battery",               "20 days",  "09/28/26", "10/23/26", "32",                "Bosch Azure Team",                               "New M365 tenant for NewCo; 3000 mailboxes; OneDrive and Teams in scope",                                    "No"),
    (36, 3, "Co-Location and Data Centre Selection (1 Regional Hub)",     "20 days",  "09/14/26", "10/09/26", "23",                "Bosch Procurement + IT",                         "Single regional co-locator; decision required by QG2; EMEA primary recommended",                           "No"),
    (37, 3, "Security Architecture Design - NewCo Battery",               "20 days",  "10/26/26", "11/20/26", "33,34",             "Bosch CISO",                                     "NewCo security architecture; independent from Bosch SOC post-Day 1",                                        "No"),
    (38, 3, "IAM and IdM Architecture Design - NewCo Battery",            "15 days",  "10/26/26", "11/13/26", "34",                "Bosch IAM Team",                                 "New IAM platform for NewCo; decouple from Bosch IAM / Saviynt",                                             "No"),
    (39, 2, "2.3 Battery IT Migration Strategy",                          "45 days",  "10/20/26", "12/21/26", "23,25",             "KPMG + All WS Leads",                            "",                                                                                                           "No"),
    (40, 3, "ERP Migration Strategy Decision - Shell Copy vs Greenfield", "20 days",  "10/20/26", "11/16/26", "25",                "ERP Architects + KPMG",                          "Decision must be made at QG2; shell copy benchmarked at 9-12 month SIT cycle",                             "No"),
    (41, 3, "Application Categorisation and Wave Planning (~200 Apps)",   "20 days",  "11/17/26", "12/14/26", "40",                "KPMG + WS Leads",                                "Wave 1 ~60 critical; Wave 2 ~80 standard; Wave 3 ~60 local and OT apps",                                   "No"),
    (42, 3, "Data Separation Rules Finalised",                            "15 days",  "11/24/26", "12/12/26", "26",                "KPMG + Legal",                                   "",                                                                                                           "No"),
    (43, 3, "TSA Service Catalogue Definition (Bosch-provided Services)", "25 days",  "10/20/26", "11/23/26", "32",                "Bosch IT + NewCo IT",                            "Catalogue all Bosch services Battery NewCo requires; define exit criteria per service line",                 "No"),
    (44, 3, "NewCo Stand-Alone Operating Model (post-TSA)",               "20 days",  "11/17/26", "12/14/26", "40,41",             "Bosch IT Architects",                            "Stand Alone: all services exit directly to NewCo; define NewCo IT operating model",                           "No"),
    (45, 2, "2.4 Client Device and Workplace Strategy",                   "20 days",  "10/20/26", "11/16/26", "23",                "Bosch CWP Team",                                 "",                                                                                                           "No"),
    (46, 3, "Client Device Inventory (~2500 Battery Devices)",            "10 days",  "10/20/26", "10/30/26", "23",                "Bosch IT + Asset Mgmt",                          "Identify device age and type; replacement hardware plan for out-of-support devices",                         "No"),
    (47, 3, "Client Migration Approach - Wave-Based Reimaging",           "10 days",  "10/31/26", "11/13/26", "46",                "Bosch CWP Team",                                 "~2500 devices across 35 sites; EMEA first then AP then AM",                                                 "No"),
    (48, 2, "2.5 Planning and Baseline",                                  "20 days",  "11/10/26", "12/03/26", "31,39",             "KPMG + IT PM",                                   "",                                                                                                           "No"),
    (49, 3, "Detailed Project Plan Development",                          "15 days",  "11/10/26", "11/28/26", "31,39",             "KPMG + IT PM",                                   "",                                                                                                           "No"),
    (50, 3, "Risk Register Baseline",                                     "12 days",  "11/10/26", "11/25/26", "39",                "KPMG + All WS Leads",                            "",                                                                                                           "No"),
    (51, 3, "OPL Establishment and Tracking Setup",                       "10 days",  "11/16/26", "11/27/26", "49",                "PMO",                                            "",                                                                                                           "No"),
    (52, 3, "Resource Plan and Budget Baseline",                          "12 days",  "11/16/26", "12/01/26", "49",                "Finance + IT PM",                                "",                                                                                                           "No"),
    (53, 2, "QG2 - Concept Quality Gate",                                 "0 days",   "11/30/26", "11/30/26", "48,44,43",          "Steering Committee",                             "Architecture approved; ERP strategy decided; WAN vendor contracted; TSA catalogue signed off; proceed to Development", "Yes"),

    # ── PHASE 3: Development and Build  01 Dec 2026 – 30 Jun 2027 ───────────
    (54, 1, "Phase 3 - Development and Build",                            "145 days", "12/01/26", "06/30/27", "53",                "All Workstreams",                                "",                                                                                                           "No"),
    (55, 2, "3.1 NewCo IT Infrastructure Build",                          "120 days", "12/01/26", "05/28/27", "53",                "Bosch Infra + Partners",                         "",                                                                                                           "No"),
    (56, 3, "WAN Provider Selection and Ordering - 35 Battery Sites",     "20 days",  "12/01/26", "12/28/26", "53",                "Bosch Procurement",                              "Order immediately after QG2; 4-6 month lead time; covers all 35 Battery sites",                              "No"),
    (57, 3, "Co-Location Data Centre Procurement - 1 Regional Hub",       "30 days",  "12/01/26", "01/12/27", "53",                "Bosch Infra",                                    "Primary EMEA co-locator for NewCo DC; connectivity to AP and AM",                                           "No"),
    (58, 3, "Active Directory Build - NewCo Battery Forest",              "30 days",  "01/13/27", "02/24/27", "56",                "Bosch AD Team",                                  "Foundation: all 3000 users and ~200 applications migrate to this new AD forest",                            "No"),
    (59, 3, "WAN Delivery and Testing - EMEA Battery Sites (~15 sites)",  "40 days",  "04/20/27", "06/16/27", "56",                "WAN Provider + Bosch Infra",                     "4-6 month lead time from Dec 2026 order; EMEA circuit activation April 2027 onwards",                        "No"),
    (60, 3, "WAN Delivery and Testing - AP Battery Sites (~12 sites)",    "50 days",  "04/20/27", "06/30/27", "56",                "WAN Provider + Bosch Infra",                     "China requires local provider; stagger by country",                                                         "No"),
    (61, 3, "WAN Delivery and Testing - AM Battery Sites (~8 sites)",     "40 days",  "04/20/27", "06/16/27", "56",                "WAN Provider + Bosch Infra",                     "Mexico legal entity confirmed before ordering; CSD leads required",                                         "No"),
    (62, 3, "LAN and WiFi Setup - Top 15 Priority Battery Sites",         "30 days",  "02/25/27", "04/07/27", "58",                "Bosch Infra",                                    "Remaining 20 sites use existing Bosch LAN under TSA until cutover",                                         "No"),
    (63, 3, "Server Infrastructure Build - NewCo Co-Lo DC",               "30 days",  "01/13/27", "02/24/27", "57",                "Bosch Infra",                                    "",                                                                                                           "No"),
    (64, 3, "M365 Tenant Provisioning - NewCo Battery (3000 Mailboxes)",  "25 days",  "01/13/27", "02/17/27", "53",                "Bosch Azure Team",                               "",                                                                                                           "No"),
    (65, 3, "Azure and Cloud Environment Setup - NewCo Battery",          "25 days",  "02/18/27", "03/24/27", "64",                "Bosch Cloud Team",                               "",                                                                                                           "No"),
    (66, 3, "Telephony Design and Platform Setup - NewCo Battery 35 Sites", "20 days","03/25/27", "04/21/27", "63",                "Bosch Telecom",                                  "Phone number porting plan; 4-8 weeks per operator per site; state-owned operators longer",                   "No"),
    (67, 3, "File Share Infrastructure - NewCo (NAS / Cloud)",            "15 days",  "02/25/27", "03/17/27", "63",                "Bosch Infra",                                    "User documents and shared drives for ~3000 Battery employees",                                               "No"),
    (68, 3, "Backup and Archiving Setup - NewCo Battery",                 "12 days",  "03/18/27", "04/02/27", "63",                "Bosch Infra",                                    "",                                                                                                           "No"),
    (69, 2, "3.2 ERP and SAP Development - NewCo Battery",               "100 days", "12/01/26", "05/14/27", "53",                "Bosch ERP Team + Migration Partner",              "",                                                                                                           "No"),
    (70, 3, "SAP System Landscape Analysis - Battery Scope",              "20 days",  "12/01/26", "12/28/26", "53",                "ERP Architects",                                 "",                                                                                                           "No"),
    (71, 3, "SAP Shell Copy Preparation - Battery Systems (NewCo)",       "40 days",  "01/13/27", "03/10/27", "70",                "Migration Partner + Bosch SAP",                  "Shell copy approach confirmed; Battery-specific systems only; disconnect from Bosch SAP",                    "No"),
    (72, 3, "SAP Interface Identification and Adaptation Plan",           "30 days",  "01/13/27", "02/24/27", "70",                "Bosch ERP Team",                                 "",                                                                                                           "No"),
    (73, 3, "SAP Authorisation Concept - Disconnect from Bosch IdM",      "25 days",  "03/11/27", "04/14/27", "71",                "Bosch SAP Security",                             "Battery user authorisations must be fully decoupled from Bosch IAM and Saviynt",                             "No"),
    (74, 3, "BW and Reporting Setup - NewCo Battery",                     "25 days",  "03/11/27", "04/14/27", "71",                "Bosch BW Team",                                  "",                                                                                                           "No"),
    (75, 3, "EDI and Integration Setup - NewCo Battery",                  "25 days",  "02/25/27", "03/31/27", "72",                "Integration Team",                               "",                                                                                                           "No"),
    (76, 3, "ERP Test Environment Setup (SIT and UAT) - NewCo",           "20 days",  "04/15/27", "05/12/27", "71",                "Migration Partner + Bosch SAP",                  "",                                                                                                           "No"),
    (77, 2, "3.3 Application Migration Preparation (~200 Battery Apps)",  "80 days",  "12/01/26", "04/08/27", "53",                "Bosch IT + KPMG",                                "",                                                                                                           "No"),
    (78, 3, "Application Inventory Finalisation (~200 Battery Apps)",     "20 days",  "12/01/26", "12/28/26", "53",                "KPMG + Bosch IT",                                "Validate LeanIX entries; add local and regional apps discovered post-QG2",                                  "No"),
    (79, 3, "Application Grouping into Migration Waves",                  "15 days",  "01/13/27", "02/03/27", "78",                "KPMG + WS Leads",                                "Wave 1 ~60 critical; Wave 2 ~80 standard; Wave 3 ~60 local and OT",                                        "No"),
    (80, 3, "Migration Package Development per Wave",                     "35 days",  "02/04/27", "03/24/27", "79",                "Bosch IT + App Owners",                          "",                                                                                                           "No"),
    (81, 3, "Custom Application Adaptation for NewCo Environment",        "25 days",  "03/10/27", "04/11/27", "79",                "Dev Teams",                                      "Re-point app configs from Bosch to NewCo domain / AD / M365 / ITSM",                                       "No"),
    (82, 3, "Integration Development (APIs and Interfaces) - NewCo",      "25 days",  "03/10/27", "04/11/27", "79",                "Integration Team",                               "",                                                                                                           "No"),
    (83, 2, "3.4 Client Workplace - 2500 Device Migration Preparation",   "50 days",  "12/01/26", "02/08/27", "53",                "Bosch CWP Team",                                 "",                                                                                                           "No"),
    (84, 3, "Client Software Management Setup (SCCM / Intune) - NewCo",  "20 days",  "12/01/26", "12/28/26", "53",                "Bosch CWP",                                      "",                                                                                                           "No"),
    (85, 3, "Device Reimaging Standard and Packaging (~2500 Devices)",    "25 days",  "01/13/27", "02/17/27", "84",                "Bosch CWP",                                      "Standard image for NewCo domain; hardware refresh for out-of-support devices",                               "No"),
    (86, 3, "Regional Wave Plan - Client Migration (EMEA / AP / AM)",     "12 days",  "12/15/26", "01/02/27", "84",                "Bosch CWP + IT PM",                              "EMEA Wave 1; AP Wave 2; AM Wave 3; stagger by site count and regional complexity",                          "No"),
    (87, 3, "User Profile and OneDrive Migration Tooling Setup",          "20 days",  "01/18/27", "02/08/27", "85",                "Bosch Azure Team",                               "",                                                                                                           "No"),
    (88, 2, "3.5 Security and IAM - NewCo Battery",                       "60 days",  "12/01/26", "02/24/27", "53",                "Bosch CISO + IAM Team",                          "",                                                                                                           "No"),
    (89, 3, "IAM Platform Deployment - NewCo Battery",                    "35 days",  "12/01/26", "01/19/27", "53",                "Bosch IAM",                                      "New IAM platform independent of Bosch Saviynt; provisioning for 3000 Battery users",                         "No"),
    (90, 3, "IT Security Concept Finalisation (incl. ISO 27001 Baseline)","20 days",  "01/20/27", "02/16/27", "89",                "Bosch CISO",                                     "NewCo CISO appointed; ISO 27001 pre-assessment; BCM and GDPR compliance",                                   "No"),
    (91, 3, "OT Security Assessment and Remediation - Battery Manufacturing", "25 days", "12/15/26", "01/19/27", "53",             "OT Security Team",                               "Battery plant OT systems; ICS/SCADA assessment; safety certification review",                                "No"),
    (92, 3, "CMDB Setup (ServiceNow or ITSM Platform) - 2500 NewCo Assets", "25 days", "01/20/27", "02/23/27", "89",              "Bosch ITSM Team",                                "",                                                                                                           "No"),
    (93, 2, "3.6 NewCo IT Organisation and Operations Setup",             "70 days",  "12/01/26", "03/10/27", "53",                "Bosch IT Org Team",                              "",                                                                                                           "No"),
    (94, 3, "NewCo IT Target Operating Model (TOM)",                      "20 days",  "12/01/26", "12/28/26", "53",                "Bosch HR + IT",                                  "NewCo IT org structure; Regional IT leads for EMEA / AP / AM",                                             "No"),
    (95, 3, "MSP and ITO Contracting - Field Support 35 Battery Sites",   "35 days",  "01/13/27", "02/28/27", "94",                "Bosch Procurement",                              "On-site support for AP and AM Battery sites; multi-language support required",                               "No"),
    (96, 3, "ITSM and ServiceNow Configuration - NewCo Battery",          "25 days",  "01/20/27", "02/23/27", "92",                "Bosch ITSM",                                     "",                                                                                                           "No"),
    (97, 3, "Help Desk Setup and Staffing - Multi-Region NewCo",          "20 days",  "02/24/27", "03/23/27", "95",                "Bosch IT Ops",                                   "Multilingual support for EMEA / AP / AM Battery users; 24x5 coverage",                                     "No"),
    (98, 2, "3.7 TSA Framework Finalisation (Bosch-provided Services)",   "55 days",  "12/01/26", "02/14/27", "53",                "Bosch IT + Legal",                               "",                                                                                                           "No"),
    (99, 3, "TSA Service Descriptions Finalised - All 35 Battery Sites",  "25 days",  "12/01/26", "01/05/27", "53",                "Bosch IT + NewCo IT",                            "Each TSA service line must have an exit date and acceptance criteria",                                       "No"),
    (100,3, "TSA SLA and KPI Framework",                                  "20 days",  "01/06/27", "02/02/27", "99",                "IT PM + Legal",                                  "",                                                                                                           "No"),
    (101,3, "TSA Governance Model (Monthly SteerCo Reviews)",             "12 days",  "02/03/27", "02/18/27", "100",               "IT PM",                                          "",                                                                                                           "No"),
    (102,3, "TSA Contracts Legal Review and Finalisation",                "20 days",  "02/03/27", "03/02/27", "100",               "Legal",                                          "",                                                                                                           "No"),
    (103,2, "QG3 - Development Quality Gate",                             "0 days",   "06/30/27", "06/30/27", "55,69,77,83,88,93,98", "Steering Committee",                         "NewCo infra ready; ERP built; app packages ready; 2500 devices packaged; TSA contracts signed; proceed to Implementation", "Yes"),

    # ── PHASE 4: Implementation  01 Jul 2027 – 30 Sep 2027 ──────────────────
    (104,1, "Phase 4 - Implementation",                                   "65 days",  "07/01/27", "09/30/27", "103",               "All Workstreams",                                "",                                                                                                           "No"),
    (105,2, "4.1 Infrastructure Cutover - 35 Battery Sites to NewCo",     "55 days",  "07/01/27", "09/12/27", "103",               "Bosch Infra + Partners",                         "",                                                                                                           "No"),
    (106,3, "WAN Cutover - EMEA Battery Sites Batch 1 (~8 sites)",        "15 days",  "07/01/27", "07/21/27", "103",               "WAN Team + Bosch Infra",                         "",                                                                                                           "No"),
    (107,3, "WAN Cutover - AP Battery Sites Batch 1 (Major Hubs ~6 sites)","15 days", "07/01/27", "07/21/27", "103",               "WAN Team + Bosch Infra",                         "AP hub sites first",                                                                                        "No"),
    (108,3, "WAN Cutover - AM Battery Sites Batch 1 (Major Hubs ~4 sites)","15 days", "07/01/27", "07/21/27", "103",               "WAN Team + Bosch Infra",                         "",                                                                                                           "No"),
    (109,3, "WAN Cutover - EMEA Battery Sites Batch 2 (Remaining ~7)",    "15 days",  "07/22/27", "08/11/27", "106",               "WAN Team + Bosch Infra",                         "",                                                                                                           "No"),
    (110,3, "WAN Cutover - AP Battery Sites Batch 2 (Remaining ~6)",      "15 days",  "07/22/27", "08/11/27", "107",               "WAN Team + Bosch Infra",                         "",                                                                                                           "No"),
    (111,3, "WAN Cutover - AM Battery Sites Batch 2 (Remaining ~4)",      "15 days",  "07/22/27", "08/11/27", "108",               "WAN Team + Bosch Infra",                         "",                                                                                                           "No"),
    (112,3, "File Share Migration to NewCo (~3000 Battery Users)",        "25 days",  "07/22/27", "08/25/27", "106",               "Bosch Infra",                                    "User documents and shared drives migration to NewCo environment",                                            "No"),
    (113,3, "Telephony Cutover to NewCo - 35 Battery Sites",              "35 days",  "08/11/27", "09/26/27", "109,110,111",       "Bosch Telecom",                                  "Staggered by operator; parallel execution across sites; 4-8 weeks per operator",                           "No"),
    (114,2, "4.2 Client Device Migration - 2500 Battery Devices",         "65 days",  "07/01/27", "09/30/27", "103",               "Bosch CWP + Regional IT",                        "",                                                                                                           "No"),
    (115,3, "Client Migration Wave 1 - EMEA Battery Hub Sites (~500 devices)","20 days","07/01/27","07/28/27","103",               "EMEA IT Team",                                   "EMEA hub sites first; ~500 devices",                                                                        "No"),
    (116,3, "Client Migration Wave 2 - AP Battery Sites (~700 devices)",  "20 days",  "07/01/27", "07/28/27", "103",               "AP IT Team",                                     "~700 AP devices; run parallel with EMEA Wave 1",                                                            "No"),
    (117,3, "Client Migration Wave 3 - EMEA Remaining Sites (~300 devices)","15 days","07/29/27","08/18/27",  "115",               "EMEA IT Team",                                   "~300 remaining EMEA devices",                                                                               "No"),
    (118,3, "Client Migration Wave 4 - AM Battery Sites (~500 devices)",  "20 days",  "07/29/27", "08/25/27", "116",               "AM IT Team",                                     "~500 AM devices",                                                                                           "No"),
    (119,3, "Client Migration Wave 5 - AP Remaining + AM Remaining (~400)","20 days", "08/19/27", "09/15/27", "117,118",           "CWP Team",                                       "~400 devices to complete all regions",                                                                      "No"),
    (120,3, "Client Migration Wave 6 - Stragglers and Exceptions (~100)", "10 days",  "09/16/27", "09/29/27", "119",               "CWP Team",                                       "~100 devices; special handling; exceptions and replacements",                                               "No"),
    (121,3, "Email and M365 Mailbox Migration (3000 Battery Mailboxes)",  "40 days",  "07/22/27", "09/15/27", "106",               "Bosch Azure Team",                               "Migrate in batches aligned with client device waves",                                                       "No"),
    (122,3, "OneDrive and User Document Migration",                       "25 days",  "08/12/27", "09/15/27", "121",               "Bosch Azure Team",                               "",                                                                                                           "No"),
    (123,2, "4.3 ERP Migration to NewCo Battery",                         "65 days",  "07/01/27", "09/30/27", "103",               "ERP Team + Migration Partner",                   "",                                                                                                           "No"),
    (124,3, "SAP Shell Copy Execution - Test Run (NewCo Battery)",        "20 days",  "07/01/27", "07/28/27", "103",               "Migration Partner + Bosch SAP",                  "",                                                                                                           "No"),
    (125,3, "SAP System Integration Test 1 (SIT1) - Battery",            "25 days",  "07/29/27", "09/02/27", "124",               "ERP Team + Business",                            "",                                                                                                           "No"),
    (126,3, "SAP Shell Copy Execution - Production Preparation",          "10 days",  "09/03/27", "09/16/27", "125",               "Migration Partner + Bosch SAP",                  "",                                                                                                           "No"),
    (127,3, "SAP System Integration Test 2 (SIT2) - Battery",            "10 days",  "09/17/27", "09/30/27", "126",               "ERP Team + Business",                            "",                                                                                                           "No"),
    (128,3, "Business User Acceptance Testing (UAT) - Battery ERP",       "15 days",  "09/03/27", "09/23/27", "125",               "Business Key Users",                             "",                                                                                                           "No"),
    (129,3, "UAT Sign-Off",                                               "0 days",   "09/23/27", "09/23/27", "128",               "Business Leads + IT PM",                         "",                                                                                                           "Yes"),
    (130,2, "4.4 Application Migration to NewCo Battery",                 "65 days",  "07/01/27", "09/30/27", "103",               "Bosch IT + App Teams",                           "",                                                                                                           "No"),
    (131,3, "Wave 1 Application Migration - Critical Battery Apps (~60)", "20 days",  "07/01/27", "07/28/27", "103",               "App Teams + KPMG",                               "",                                                                                                           "No"),
    (132,3, "Wave 2 Application Migration - Standard Apps (~80)",         "25 days",  "07/29/27", "09/02/27", "131",               "App Teams",                                      "",                                                                                                           "No"),
    (133,3, "Wave 3 Application Migration - Local and OT Apps (~60)",     "25 days",  "09/03/27", "10/07/27", "132",               "App Teams",                                      "Regional and OT-linked apps; some may require TSA extension if not Day 1 ready",                            "No"),
    (134,3, "End-to-End Integration Testing - NewCo Battery",             "15 days",  "08/19/27", "09/08/27", "132",               "Test Team + Business",                           "",                                                                                                           "No"),
    (135,3, "Regression Testing Sign-Off",                                "0 days",   "09/08/27", "09/08/27", "134",               "Test Manager",                                   "",                                                                                                           "Yes"),
    (136,2, "4.5 Day 1 Cutover Preparation",                              "25 days",  "09/01/27", "09/30/27", "129,135,103",       "IT PM + All WS",                                 "",                                                                                                           "No"),
    (137,3, "Cutover Plan Finalisation",                                  "10 days",  "09/01/27", "09/12/27", "103",               "IT PM + WS Leads",                               "",                                                                                                           "No"),
    (138,3, "End-User Communication Plan (3000 Battery Users / 35 Sites)","15 days",  "09/01/27", "09/19/27", "137",               "Comms + Regional IT",                            "Multi-language; EMEA + AP + AM; Battery users only",                                                        "No"),
    (139,3, "Dress Rehearsal and Cutover Simulation",                     "5 days",   "09/15/27", "09/19/27", "137",               "All WS Leads",                                   "",                                                                                                           "No"),
    (140,3, "Help Desk 24x7 Activation and Training - NewCo Battery",    "10 days",  "09/15/27", "09/26/27", "137",               "IT Ops",                                         "Multi-region time zone coverage for Battery users",                                                         "No"),
    (141,3, "Go No-Go Readiness Assessment",                              "0 days",   "09/15/27", "09/15/27", "138,139,140",       "Steering Committee",                             "",                                                                                                           "Yes"),
    (142,2, "QG4 - Implementation Quality Gate - Go / No-Go",            "0 days",   "09/15/27", "09/15/27", "141",               "Steering Committee",                             "2500 clients migrated; ERP live in NewCo; apps live in NewCo; UAT passed; cutover plan approved; Day 1 confirmed", "Yes"),

    # ── PHASE 5: GoLive and Programme Closure  01 Oct 2027 – 31 Dec 2027 ────
    (143,1, "Phase 5 - GoLive and Programme Closure",                     "65 days",  "10/01/27", "12/31/27", "142",               "All Workstreams",                                "",                                                                                                           "No"),
    (144,2, "5.1 Day 1 GoLive Activities",                                "5 days",   "10/01/27", "10/07/27", "142",               "IT PM + Business",                               "",                                                                                                           "No"),
    (145,3, "Day 1 - NewCo Battery IT GoLive (Legal Separation Effective)","0 days",  "10/01/27", "10/01/27", "142",               "Executive Leadership",                           "Battery IT fully separated from Bosch; NewCo IT independent from this date",                                "Yes"),
    (146,3, "Network Domain Cutover to NewCo Active Directory",           "2 days",   "10/01/27", "10/02/27", "145",               "Bosch Infra",                                    "",                                                                                                           "No"),
    (147,3, "ERP Day 1 Go-Live Activation - Battery SAP NewCo",           "2 days",   "10/01/27", "10/02/27", "145",               "ERP Team",                                       "",                                                                                                           "No"),
    (148,3, "Application Day 1 Activation - All Battery Regions",         "2 days",   "10/01/27", "10/02/27", "145",               "App Teams",                                      "",                                                                                                           "No"),
    (149,3, "Bosch TSA Residual Services Activated (Minimal Scope)",      "1 days",   "10/01/27", "10/01/27", "145",               "Bosch IT + NewCo IT",                            "TSA clock starts 01 Oct 2027; expires 31 Dec 2027; only residual services below full separation threshold",  "No"),
    (150,3, "User Go-Live Communication (3000 Battery Users)",            "1 days",   "10/01/27", "10/01/27", "145",               "Comms + Regional IT",                            "",                                                                                                           "No"),
    (151,3, "Help Desk 24x7 Live - NewCo Battery",                        "1 days",   "10/01/27", "10/01/27", "145",               "IT Ops",                                         "",                                                                                                           "No"),
    (152,2, "5.2 Hypercare - 65 Working Days",                            "65 days",  "10/01/27", "12/31/27", "144",               "All WS Leads + IT Ops",                          "",                                                                                                           "No"),
    (153,3, "Daily Operations Review Meetings (Regional Standups)",       "65 days",  "10/01/27", "12/31/27", "144",               "IT PM + Regional WS Leads",                      "EMEA + AP + AM standup cadence; Battery NewCo focus",                                                       "No"),
    (154,3, "Incident Management and P1/P2 Issue Resolution",             "65 days",  "10/01/27", "12/31/27", "144",               "IT Ops + Help Desk",                             "",                                                                                                           "No"),
    (155,3, "Performance Monitoring and TSA SLA Tracking",                "65 days",  "10/01/27", "12/31/27", "144",               "IT Ops",                                         "Bosch residual TSA SLA compliance tracked from Day 1; exit by Dec 2027",                                   "No"),
    (156,3, "Issue Backlog Management and Prioritisation",                "65 days",  "10/01/27", "12/31/27", "144",               "IT PM",                                          "",                                                                                                           "No"),
    (157,3, "Hypercare Close - Formal Sign-Off",                          "0 days",   "12/31/27", "12/31/27", "153,154,155,156",   "Steering Committee",                             "",                                                                                                           "Yes"),
    (158,2, "5.3 TSA Exit and Bosch Service Termination",                 "60 days",  "10/01/27", "12/24/27", "144",               "Bosch IT + NewCo IT",                            "",                                                                                                           "No"),
    (159,3, "TSA Exit Planning per Service",                              "15 days",  "10/01/27", "10/21/27", "144",               "IT PM + Bosch IT",                               "Define exit criteria per remaining TSA service; agree acceptance tests",                                     "No"),
    (160,3, "TSA Service Exit Wave 1 - Infrastructure Services",          "20 days",  "10/22/27", "11/18/27", "159",               "Bosch IT + NewCo IT",                            "",                                                                                                           "No"),
    (161,3, "TSA Service Exit Wave 2 - Application and ERP Services",     "20 days",  "11/19/27", "12/16/27", "160",               "Bosch IT + NewCo IT",                            "",                                                                                                           "No"),
    (162,3, "TSA Exit Confirmation (All Bosch Services Terminated)",      "0 days",   "12/31/27", "12/31/27", "161",               "Bosch + NewCo Executive",                        "",                                                                                                           "Yes"),
    (163,2, "5.4 Programme Closure",                                      "20 days",  "12/08/27", "12/31/27", "157",               "IT PM + KPMG",                                   "",                                                                                                           "No"),
    (164,3, "Lessons Learned Workshop (All Regions)",                     "5 days",   "12/08/27", "12/12/27", "157",               "All WS Leads",                                   "",                                                                                                           "No"),
    (165,3, "Programme Closure Report",                                   "10 days",  "12/13/27", "12/26/27", "164",               "IT PM + KPMG",                                   "",                                                                                                           "No"),
    (166,3, "Final Programme Sign-Off",                                   "0 days",   "12/31/27", "12/31/27", "165",               "Executive Leadership",                           "",                                                                                                           "Yes"),
    (167,2, "QG5 - Programme Closure Quality Gate",                       "0 days",   "12/31/27", "12/31/27", "157,162,166",       "Steering Committee",                             "Hypercare stable; TSA fully exited; NewCo IT fully independent; AlphaX programme formally closed",          "Yes"),
]

HEADERS = ["ID", "Outline Level", "Name", "Duration", "Start", "Finish",
           "Predecessors", "Resource Names", "Notes", "Milestone"]


def write_csv(path: Path):
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(HEADERS)
        for t in TASKS:
            writer.writerow(list(t))
    print(f"CSV written: {path}  ({len(TASKS)} tasks)")


if __name__ == "__main__":
    from datetime import datetime as _dt
    _t0 = _dt.now()
    print(f"Started : {_t0.strftime('%Y-%m-%d %H:%M:%S')}")
    try:
        # 1. Write CSV
        write_csv(CSV_PATH)

        # 2. Generate XML via generate_msp_xml.py
        import subprocess
        result = subprocess.run(
            [sys.executable,
             str(HERE / "generate_msp_xml.py"),
             "--csv", str(CSV_PATH),
             "--out", str(XML_PATH)],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print(result.stdout.strip())
            print(f"\nXML written: {XML_PATH}")
        else:
            print("generate_msp_xml.py error:")
            print(result.stderr)
            sys.exit(1)
    finally:
        _t1 = _dt.now()
        print(f"Finished: {_t1.strftime('%Y-%m-%d %H:%M:%S')}  ({(_t1-_t0).total_seconds():.1f}s elapsed)")
